using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AchievementClass
{
    public enum Achievements
    {
        Toujiangosaurus = 0
        Yutyrannus,
        Amargasaurus,
        Taperjara,
        Carnotaurus,
        Nasutoceratops,
        Welcome_to_Jurassic_Park,
        Good_start,
        Fast_and_Furious,
        Is_it_a_bird?,
        Ceratosaurus,
        Pachycephalosaurus,
        Baryonyx,
        Say_it_again?,
        Ankylosaurus,
        Parasaurolophus,
        Brontosaurus,
        Compsognathus,
        Brachiosaurus,
        Spinosaurus,
        Gallimimus,
        Stegosaurus,
        Allosaurus,
        Corythosaurus,
        Camarasaurus,
        IS_it_a_plane?,
        Hail_to_the_King,
        Acrocanthosaurus,
        Torosaurus,
        Troodon,
        Ouranosaurus,
        Iguanodon,
        Albertosaurus,
        Pachyrhinosaurus,
        Edmontosaurus,
        Dryosaurus,
        Giganotosaurus,
        Rajasaurus,
        Shunosaurus,
        Suchomimus,
        Koolasuchus,
        Archelon,
        Protosphyraena,
        Pliosaurus,
        Trinacromerum,
        Colossal_Squid,
        Xiphactinus,
        Helicoprion,
        Elasmosaurus,
        Sea_Scorpion,
        Geosaurus,
        Dakosaurus,
        Megalodon,
        Mosasaurus,
        Henodus,
        Dunkleosteus,
        Ammonite,
        Kronosaurus,
        Platecarpus,
        Tylosaurus,
        Leedsichtys,
        Gillicus,
        Basilosaurus,
        Psephoderma,
        Leptocleidus,
        Orthoceras,
        Hainosaurus,
        Shonisaurus,
        Anomalocaris,
        Styxosaurus,
        Bananogmius,
        Leviathan,
        Ophtalmosaurus,
        Mauisaurus,
        Hybodus,
        Odobenocetops,
        Dolichorhynchops,
        Enchodus,
        Metriorhynchus,
        Coryphodon,
        Synthetoceras,
        Titanoboa,
        Amphicyon,
        Procoptodon,
        Gigantopithecus,
        Indricotherium,
        Andrewsarchus,
        Mastodon,
        Terror_Bird,
        Dodo,
        Smilodon,
        Elasmotherium,
        Daeodon,
        Amebelodon,
        Entelodon,
        Woolly_Mammoth,
        Megaloceros,
        Megistotherium,
        Unintatherium,
        Aepycamelus,
        Eremotherium,
        Gastornis,
        Sarkastodon,
        Meiolania,
        Chalicotherium,
        Thylacosmilus,
        Peltephilus,
        Moeritherium,
        Arsinoitherium,
        Kelenken,
        Kaprosuchus,
        Megalania,
        Doedicurus,
        Hyaenodon,
        Diprotodon,
        Platybelodon,
        Deinosuchus,
        Marsupial_Lion,
        Veteran_battler,
        Dont_stop_me_now
    }
    public Achievements achievement {get;set;}
    public bool isunlocked {get;set;}

    public AchievementClass(bool isunlocked_,Achievements achievements)
    {   
        this.achievement = achievements;
        this.isunlocked = isunlocked_;
        return;
    }
    
}
